#ifndef _COMAND_TYPES_H_
#define _COMAND_TYPES_H_

#define MESSAGE_CMD_APP_STATUS	    	1
#define MESSAGE_CMD_VERSION				3
#define MESSAGE_CMD_LAND_MODE			5
#define MESSAGE_CMD_PLAY_STATUS			12
#define MESSAGE_CMD_MIRROR_SUPPORT		16
#define MESSAGE_CMD_RESEND_SPS			17
#define MESSAGE_CMD_HEARTBEAT			10
#define MESSAGE_CMD_UPGRADE             13

#endif /* _COMAND_TYPES_H_ */
